### ISSUE TITLE
新版sdk里pfop接口global缺失导致的问题

### ISSUE THREAD

**Issue by wefound** [qiniu/php-sdk#100]
在conf.php中， $QINIU_API_HOST、$QINIU_IOVIP_HOST两个变量没有声明全局，导致封装后的qiniu接口，被autoload时，作用域只限于loader方法内部。
而Qiniu_Pfop这些工具类里，即使加了global，也无法正确使用。
php执行到curl_exec时，curl返回 curl malformed

**Comment by longbai** [comment]
已经修复，代码在v6 分支，v7 版本已经没有这种方式的全局变量了。
