### ISSUE TITLE
上传出错，返回"Could not resolve host: up.qiniu.com"

### ISSUE THREAD

**Issue by wuguobao** [qiniu/php-sdk#127]
Qiniu\Http\Errorresponse:
body: null
duration: 0.005
error: "Could not resolve host: up.qiniu.com"
headers: []
statusCode: -1
Qiniu\Http\Errorurl: "http://up.qiniu.com"

是什么原因？

**Comment by wuguobao** [comment]
ubuntu 系统，要怎么设置？

**Comment by longbai** [comment]
域名解析失败，麻烦看下您的系统dns 服务器配置
