### ISSUE TITLE
重新转码

### ISSUE THREAD

**Issue by jackyang1984** [qiniu/php-sdk#131]
语音上传之后，显示转码失败，多次重新上传后，还是转码失败。相同的语音文件，换一台电脑上传就会成功

**Comment by rwifeng** [comment]
你好， 可否将出错信息给下？ 还有你的语音文件的外链。

**Comment by jackyang1984** [comment]
没有出错信息，就是上传语音文件的时候，先是显示正在转码，然后过一会就显示重新转码。

**Comment by rwifeng** [comment]
可否给我下转码信息的链接？不然这边没法排查。

**Comment by jackyang1984** [comment]
array(
   'Err' => 'select/poll returned error',
   'Reqid' => NULL,
   'Details' => NULL,
   'Code' => 0,
)

**Comment by rwifeng** [comment]
这个错误没有遇到过，查了下应该是上传的内容太大了。具体链接可以参考：http://stackoverflow.com/questions/22656556/php-curl-errors-occasionally-select-poll-returned-error

要不你将代码和文件发我下， 我看下是否可以重现。 或者加我qq：626893266

**Comment by jackyang1984** [comment]
array (
  0 => 55,
  1 => 'select/poll returned error',
)

应该不会是文件大的原因，因为同样的文件，换一台电脑就没问题，刚才这个error code（55） 是因为网络的问题

**Comment by rwifeng** [comment]
http://elsonsolano.com/amazon-s3-when-creating-an-object-it-throws-a-curl-error/
https://forums.aws.amazon.com/thread.jspa?threadID=74609
