### ISSUE TITLE
Move phpcs dependencies to "-dev" array

### ISSUE THREAD

**Issue by gaomd** [qiniu/php-sdk#147]
In the `composer.json`

    "require": {
        "php": ">=5.3.3",
        "squizlabs/php_codesniffer": "~2.3"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.0"
    },

`squizlabs/php_codesniffer` should be moved to `require-dev`.

**Comment by longbai** [comment]
说得对，我们改下

**Comment by rwifeng** [comment]
https://github.com/qiniu/php-sdk/pull/148
