### ISSUE TITLE
fetch 无法上传到空字符串的key（即当首页用）

### ISSUE THREAD

**Issue by sinkcup** [qiniu/php-sdk#160]
访问一个bucket时，空字符串的文件会作为首页，但fetch无法上传指定空key。

**Comment by lilanjun2016** [comment]
不建议使用这样的方式，我们现在空间中的index.html文件可以设置为默认首页。

**Comment by sinkcup** [comment]
那如何解决 example.com 和 example.com/index.html 两个地址内容相同的问题呢？按照规范，不应该有任何两个地址提供重复内容，会导致网站PR下降的。

**Comment by lilanjun2016** [comment]
回您的源站处理。您的源站做下设置可以避免您说的问题，提升PR值。加速jss,cs，jpg之类的文件。

**Comment by sinkcup** [comment]
fetch是操作云存储，不存在源站。

**Comment by lilanjun2016** [comment]
是的，是抓取资源到空间。
