### ISSUE TITLE
7.0.6中的PersistentFop参数pipeline和notify_url失效

### ISSUE THREAD

**Issue by abcsun** [qiniu/php-sdk#167]
- 7.0.0版本中使用的pipeline和notify_url参数有效。
- 7.0.6版本中这两个参数失效。
- 代码位置https://github.com/qiniu/php-sdk/blob/v7.0.6/src/Qiniu/Processing/PersistentFop.php#L68

**Comment by longbai** [comment]
收到，我们看下

**Comment by 712163** [comment]
7.0.6 无效，无效，解决了吗？烦死了，测试了N多次，搞了几天，以为我程序出问题了，上线基本功能都能出错。怎么测试的？无语。。。

**Comment by rwifeng** [comment]
你好，已修复，麻烦使用最新的sdk， 多谢您的反馈。

**Comment by longbai** [comment]
fixed #170 ，不好意思，给您带来不便，十分抱歉。

**Comment by longbai** [comment]
release 7.0.7
