### ISSUE TITLE
ResumeUploader 中的inputStream 能否不执行fclose

### ISSUE THREAD

**Issue by callmez** [qiniu/php-sdk#168]
通常这个的resource是用户传过来的,决定权也应该是在用户手中(如果有后续操作的情况下);

能否不执行fclose 或则 放到析构函数中执行?

偏偏classs 又final了,, 想复写都不行....

**Comment by longbai** [comment]
收到，我们看下

**Comment by longbai** [comment]
哦，我当初设计的这个uploader是内部类，用户就只要使用uploadmanager 就好了，不应该直接使用resumeuploader, 不过您说的是问题，从对称的角度，是该外面释放。我来改下，但还是不建议直接使用 :)

**Comment by callmez** [comment]
所以我建议是如果确实不准备放开的话, 可以在析构中 释放

```php
public function __destruct()
    {
        if (is_resource($this->inputStream)) {
            fclose($this->inputStream);
        }
    }
```

**Comment by longbai** [comment]
不在析构，就在uploadmanager里释放。哪里调用，哪里释放。

**Comment by longbai** [comment]
fixed in #169
