### ISSUE TITLE
put上传相同key文件不会刷新

### ISSUE THREAD

**Issue by lyt8384** [qiniu/php-sdk#173]
如果覆盖上传相同名字的key，在管理后台是可以看到上传成功的，但是实际上并没有刷新，访问到的还是以前的图片。
这个问题在删除请求的时候同样存在。
貌似是最近出来的，需要配合刷新接口去处理？
SDK需要增加刷新的操作方法

**Comment by longbai** [comment]
这个需要刷新cdn才行

**Comment by lyt8384** [comment]
以前是不需要的，实际上很多场景会要覆盖之前的图。
最近七牛改了CDN之后貌似就是需要的了。
貌似是有配套的API出来的。
PHP-SDK里面是应该需要集成的

**Comment by lilanjun2016** [comment]
是有刷新接口的，您换图的时候再调用刷新方法

**Comment by rwifeng** [comment]
可以参考cdn的刷新方法：
https://github.com/qiniu/php-sdk/blob/master/src/Qiniu/Cdn/CdnManager.php

文档： https://developer.qiniu.com/fusion/api/1229/cache-refresh
