### ISSUE TITLE
policy callbackBody callback给post 给app中mineType 多了一个冒号 , laravel 5.2 最新xampp

### ISSUE THREAD

**Issue by JJJJJJJerk** [qiniu/php-sdk#175]
`$policy = array(
            //'returnUrl' => route('image.index'),
            'callbackUrl' => 'http://***.****.***/image/callback',
            'callbackBody' => 'filename=$(fname)
                               &filesize=$(fsize)
                               &bucket=$(bucket)
                               &key=$(key)
                               &description=$(x:description)
                               &mimeType:$(mimeType)
                               &imageInfo=$(imageInfo)
                               &exif=$(exif)
                               ',
            //设置application/json格式回调
        );

`
返回表单 mineType 格式化成json有误
`{"bucket":"eztvimg\n                               ","description":"jjj\n                               ","exif":"\n                               ","filename":"100_5622.jpg\n                               ","filesize":"35840\n                               ","imageInfo":"{\"colorModel\":\"ycbcr\",\"format\":\"jpeg\",\"height\":441,\"width\":358}\n                               ","key":"Ftmzywa3BwLxqVolnkeS7uDAbOYI\n                               ","mimeType:image/jpeg\n_______________________________":""
`

**Comment by JJJJJJJerk** [comment]
","mineType:image/jpeg\n_______________________________":""

返回去返回多了一个冒号!!!!!

**Comment by JJJJJJJerk** [comment]
![qq20160411-0](https://cloud.githubusercontent.com/assets/8449878/14424084/b9c2328a-0011-11e6-8012-907cd2f0404f.png)

**Comment by songfei9315** [comment]
&mimeType:$(mimeType)
这里你先改成这样再试试
&mimeType=$(mimeType)

**Comment by JJJJJJJerk** [comment]
确实是我的失误
