### ISSUE TITLE
上传成功后，怎么返回的数组？

### ISSUE THREAD

**Issue by ycjcl868** [qiniu/php-sdk#178]
![73f6ee8c-c314-4db8-9445-6bc9f5f502f1](https://cloud.githubusercontent.com/assets/13595509/15649066/47d9652e-26a1-11e6-9ca3-e87aba9943d9.png)
 前端ajax上传文件，返回的不是json数据，问下怎样才能返回json数据？

**Comment by justinyuan** [comment]
上传token中指定callbackurl，然后用callbackurl返回application/json的Content-Type的json结构给七牛，七牛会帮你投递到客户端
