### ISSUE TITLE
服务器接收到的回调请求头中没有HTTP_AUTHORIZATION

### ISSUE THREAD

**Issue by cloudsthere** [qiniu/php-sdk#181]
$_SERVER数组中没有HTTP_AUTHORIZATION索引， 有一个HTTP_X_REQID
file_get_contents('php://input')能获取成功

```
// 服务器callback.php 代码
$content = var_export($_SERVER, true);
file_put_contents('notify', $content);
```

**Comment by cloudsthere** [comment]
还有问题，使用 http://fusion.qiniuapi.com/refresh 接口刷新缓存，传参时使用 urls 没问题， 但使用 dirs 就返回 400038, refresh dir authority error

**Comment by zhanghan1212** [comment]
七牛的persistentNotifyUrl	  回调没有鉴权的

**Comment by jiaojunjiahanlin** [comment]
@cloudsthere  刷新接口需要单独开权限，可以去我们的工单中提交说明一下需要开通的情况，其次这个是我们的提示不到位。这块我们看下是否后期开通刷新权限，并开启目录刷新限额。

**Comment by jamguozhijun** [comment]
@cloudsthere try apache_request_headers()

**Comment by nnmer** [comment]
@jiaojunjiahanlin 一年过去了，有没有开通权限？
我发现一样的问题。 refresh urls 没有问题但是refresh dirs 一直退 400038 "error": "refresh dir authority error"。 测试的在 postman， 不要说是代码不对，看起来是你们API接口有问题

如果没有开通refresh dirs 权限那为什么在文档写了？

**Comment by rwifeng** [comment]
@nnmer  可以工单联系下 技术支持 https://support.qiniu.com/tickets/category
目录刷新 属于较危险操作， 操作需要谨慎。
