### ISSUE TITLE
PersistFop 并不支持一次传入多个fops

### ISSUE THREAD

**Issue by elespec** [qiniu/php-sdk#185]
pfop->execute($key, $fops);
fops不支持一次传入多个,传入多个一次只执行一个;

应该支持传入多个,然后分多个队列返回,感觉是服务接口禁止了这种请求

**Comment by jiaojunjiahanlin** [comment]
@elespec 提供下你传入的参数值，我们这里测试下。这种情况应该不会出现，我们这里是测试过，才发布的。java sdk之前也报过类似的错误，，是否是使用姿势的问题呢。
