### ISSUE TITLE
Zone缓存文件这个路径，通常的配置应该是没有写入权限的

### ISSUE THREAD

**Issue by mortyu** [qiniu/php-sdk#198]
```
private function hostCacheFilePath()
{
    $home = getenv('HOME');
    return $home . '/.qiniu_phpsdk_hostscache.json';
}
```

**Comment by longbai** [comment]
这是个问题，我们处理下

**Comment by 86849180** [comment]
我也遇到了这个问题

**Comment by xfstart07** [comment]
同样遇到了

**Comment by piaoxuedtian** [comment]
1、同样问题
2、在设置HOME环境变量的目录可读写的以后
$path = $this->hostCacheFilePath();
        if (!file_exists($path)) {
            return;
        }
如果没有文件会直接返回，导致后面的$this->hostCache 还是 null. 最直接的影响就是
if (!array_key_exists($key, $this->hostCache)) {  的第二个参数为null报错！

**Comment by zgldh** [comment]
莫名其妙搞什么缓存。现在只能先退回 7.0.8

**Comment by yangliulnn** [comment]
ErrorException in Zone.php line 150:
file_put_contents(/.qiniu_phpsdk_hostscache.json): failed to open stream: Permission denied

**Comment by 86849180** [comment]
怎么还没更新。。。

**Comment by dongkaipo** [comment]
+1

**Comment by dongkaipo** [comment]
@mortyu 怎么解决的?

**Comment by 86849180** [comment]
@dongkaipo  sdk已经更新

**Comment by dongkaipo** [comment]
@86849180 哈哈哈，多谢， 🙏
