### ISSUE TITLE
如何上传文件到最近的七牛云节点？

### ISSUE THREAD

**Issue by iflamed** [qiniu/php-sdk#200]
最近我发现服务器端的文件上传到七牛云比较慢，然后就仔细查了一下。可能上传节点的位置有关系。

我用的是ucloud 的广州机房。自己设置百度、阿里公共dns 都没有解析到最近的广州上传节点。在不自己设置dns的情况下，ucloud 提供的dns 也没有解析到最近的上传节点。我通过在ping.chinaz.com 查到up.qiniu.com 在广州有一个上传节点（219.135.102.35）与我服务器的ping 延时在2～5ms 之间。在我hosts 设置了这一个节点之后，上传速度明显稳定了很多。

希望PHPSDK 能够提供俩功能吧：

1. 提供设置上传到源站或者CDN 站点的选项；
2. 提供获取最近的上传节点接口，上传的时候使用最近的节点上传（部分DNS 解析不可靠的感觉）。

顺便问问，其他同学如何解决的这个问题或者有没有遇到类似的问题？

**Comment by lilanjun2016** [comment]
华东地区：
上传源站域名：up.qiniu.com
上传CDN站点域名：upload.qiniu.com
