### ISSUE TITLE
请问如何设置覆盖上传？

### ISSUE THREAD

**Issue by fengbingji** [qiniu/php-sdk#205]
请问如何设置覆盖上传（key值一样）？

**Comment by longbai** [comment]
请参考上传策略 policy 的文档

**Comment by rwifeng** [comment]
可以参考：https://developer.qiniu.com/kodo/manual/1206/put-policy
scope字段：
<bucket>:<key>，表示只允许用户上传指定 key 的文件。在这种格式下文件默认允许修改，若已存在同名资源则会被覆盖。如果只希望上传指定 key 的文件，并且不允许修改，那么可以将下面的 insertOnly 属性值设为 1。
