### ISSUE TITLE
不适用autoload 会提示functions.php中的方法不存在

### ISSUE THREAD

**Issue by gaizhixin** [qiniu/php-sdk#207]
框架使用的TP5 
`	use Qiniu\Storage\UploadManager;
	use Qiniu\Auth;
	use Qiniu\Storage\BucketManager;`
使用的命名空间

`	    				$upManager = new UploadManager();
					    $auth = new Auth(Config::get('Qiniu.accessKey'), Config::get('Qiniu.secretKey'));
					    $token = $auth->uploadToken(Config::get('Qiniu.bucket'));
					    list($ret, $error) = $upManager->put($token, $info->getFilename(), $info->getSaveName());
					    if ($err !== null) {
						    unlink($info->getSaveName());
						}else{
							unlink($info->getSaveName());//删除本地服务器的图片
							$hisImg = Db::name('user')->where(array('id'=>$uid))->value('user_img');
							$auth = new Auth(Config::get('Qiniu.accessKey'), Config::get('Qiniu.secretKey'));
							$bucketMgr = new BucketManager($auth);
							if ($hisImg) {
								$bucketMgr->delete(Config::get('Qiniu.bucket'), $hisImg);
							}
							$res = Db::name('user')->where(array('id'=>$uid))->setField('user_img',$info->getFilename());
							if($res)
							{
								$arr = array('code'=>'ok','msg'=>'上传成功','cover'=>'http://o6wndwjxn.qnssl.com/'.$info->getFilename());
							}else{
								$bucketMgr->delete(Config::get('Qiniu.bucket'), $info->getFilename());
								$arr = array('code'=>'fail','msg'=>'上传失败');
							}
						}`
传至七牛的代码

**Comment by lilanjun2016** [comment]
目前出现的问题是什么，有没有详细的报错信息。

**Comment by gaizhixin** [comment]
有的 没有找到 Qiniu\json_decode()这个方法

**Comment by lilanjun2016** [comment]
在qiniu/funcitons.php中有该方法，是使用examples中的demo直接使用的么

**Comment by gaizhixin** [comment]
@lilanjun2016 我也找到了该方法 我直接使用了readme 的命名空间 然后实例化的类 现在走到了functions中我的类是加载到了应该

**Comment by gaizhixin** [comment]
@lilanjun2016 现在提示方法找不到也是不知为何 因为那是sdk自己调用的 既然开放出来了 不可能有这种问题

**Comment by gaizhixin** [comment]
@lilanjun2016 我直接把src中的Qiniu目录拿了出来 放到了TP5的扩展目录中

**Comment by lilanjun2016** [comment]
在提供的sdk中有一个文件夹examples，里面是提供的例子，你可以试下。

**Comment by gaizhixin** [comment]
@lilanjun2016 恩我知道 如果用autoload我知道 现在想试下命名空间

**Comment by rwifeng** [comment]
@gaizhixin  autoload中有对工具函数有单独的require ， 看下能否解决你的问题
具体参考：https://github.com/qiniu/php-sdk/blob/master/autoload.php
