### ISSUE TITLE
php-unit 的使用

### ISSUE THREAD

**Issue by magichan** [qiniu/php-sdk#212]
根据 README ，在 app 的根目录中初始化了 composer ,并且安装了 php-unit 和 php-sdk,
一开始 php-sdk 的 uploadToken 一直生成不了，计划上使用 phpunit 跑一下 php-sdk 的 test 文件。

在 app 的根目录运行
```
./vendor/bin/phpunit tests/Qiniu/Tests/
```
获得以下错误
```
Cannot open file "tests/Qiniu/Tests/.php".
```
尝试制定运行的 test 文件
```
./vendor/bin/phpunit ./vendor/qiniu/php-sdk/tests/Qiniu/Tests/AuthTest.php
```
运行结果为
```
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /var/www/html/qiniu_PHP_SDK/vendor/qiniu/php-sdk/tests/Qiniu/Tests/AuthTest.php on line 22
```
故想问一下，如何正确使用 `php_unit` 测试 `qiniu/php-sdk`

**Comment by rwifeng** [comment]
这边有测试代码：https://github.com/qiniu/php-sdk/blob/master/.travis.yml
./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover tests/Qiniu/Tests/

你可以尝试下。sdk本身应该没有什么问题。
你这边具体的问题：> uploadToken 一直生成不了
有没有具体的报错信息， 或者贴下你的代码。

**Comment by magichan** [comment]
upToken 的问题已解决，是自己没有注意到运行环境需要一个库而已。

**Comment by rwifeng** [comment]
嗯， 有其他问题再反馈下。
