### ISSUE TITLE
需要我给你们重新写吗？写的这么垃圾

### ISSUE THREAD

**Issue by medz** [qiniu/php-sdk#216]
同标题。

**Comment by longbai** [comment]
请问一下，是哪里的问题，能麻烦说一下么？

**Comment by medz** [comment]
。。。。不是我发的～小伙伴整我。。。发的 issues

**Comment by medz** [comment]
没有删除按钮～尴尬了～

**Comment by medz** [comment]
好吧～刚小伙伴告诉我了～
来说下小伙伴说的“垃圾”吧～首先，代码严重缺少注释，其次，代码注释和官方文档的对应比较少，无描述，参数描述不准确。

其次，既然使用 composer 了还保留 自己封装的 autoload 早已过时，对于http请求的封装，也不是很好。问题挺多的。

**Comment by longbai** [comment]
第一点 我们会来完善。 第二点 保留这个主要为没用composer的用户准备。第三点 能麻烦说的详细些么？

**Comment by medz** [comment]
@longbai 第三点，指的是，对于接口的请求，以及请求状态的管理，以及异常抛出的处理，你们的代码中只是简单的请求接口，并没有深层次的处理http状态错误，当然，如果能完全的使用 composer 这一问题可以使用第三方 http-client解决～望参考，php 早已进入 composer 时代，不使用 composer 的也不会来 github 的～这部分用户极少。顺便说一点。。。这个帖子真的不是我开的。。。主要是你们的sdk把我小伙伴气到了。。。然后忘记是借我的电脑。。。就发了，发了才反应过来不是他的。。。。我是冤枉的呀～
