### ISSUE TITLE
上传相同的文件时候，偶尔出现file exists 的异常

### ISSUE THREAD

**Issue by m908852884** [qiniu/php-sdk#217]
问题：上传相同的文件时候，偶尔出现file exists 的异常
code
$uploadMgr = new UploadManager();
list($ret, $err) = $uploadMgr->putFile();
if ($err !== null) {}

**Comment by KevinChenQiniu** [comment]
要覆盖上传的话，要在 uptoken 的 putpolicy 的 scope 字段里携带 key ，参考：
https://developer.qiniu.com/kodo/manual/1206/put-policy

**Comment by phpyii** [comment]
我也遇到了，测了半天感觉是因为只要你本地的文件路径一样就提示文件已存在。E:/1.jpg 如果你重新换个图片还是E:/1.jpg 就提示已经存在了
