### ISSUE TITLE
阿里云虚拟主机上报错，.qiniu_phpsdk_hostscache.json这个文件没有写入权限

### ISSUE THREAD

**Issue by mkanako** [qiniu/php-sdk#221]
/src/Qiniu/Zone.php
这个函数
private function hostCacheFilePath()
    {
        return sys_get_temp_dir() . '/.qiniu_phpsdk_hostscache.json';
    }
.qiniu_phpsdk_hostscache.json这个文件不知道什么原因没有写入权限，读是ok的，但是之前一直运行得好好的
我随便在sys_get_temp_dir()下面读写其他文件都正常，实在是醉了
这种情况，sdk能处理下么

**Comment by mkanako** [comment]
额，没研究细，这不是.的问题，不知道出于什么原因.qiniu_phpsdk_hostscache.json这个文件没有权限写入，所以报错，之前一直运行得好好的啊

**Comment by rwifeng** [comment]
这个问题现在还在么？

**Comment by mkanako** [comment]
@rwifeng 还在，我只能是把路径改掉了，要sdk处理这种情况估计很蛋疼，哈哈
