### ISSUE TITLE
releases 版本

### ISSUE THREAD

**Issue by nnmer** [qiniu/php-sdk#223]
Hi，
你们现在已经加了CDNmanager 功能在master分支。 什么时候弄7.1.4 版本？ 7.1.3 发布了6月之前

**Comment by jemygraw** [comment]
已发布了7.1.4

**Comment by nnmer** [comment]
没有发布。 没有7.1.4 tag, 没有 release, packagist 也没有7.1.4

BTW, you may merge the [PR#224](https://github.com/qiniu/php-sdk/pull/224)  into 7.1.4
