### ISSUE TITLE
图片合成水印时会出现加不上水印的问题

### ISSUE THREAD

**Issue by Agzer0** [qiniu/php-sdk#233]
策略：
imageMogr2/autoorient/format/jpg/thumbnail/750x/gravity/Center/crop/750x422|watermark/1/image/<image>/gravity/NorthWest/dx/0/dy/0|saveas/<saveas>

不太清楚是受到哪些因素的干扰，上传png和jpg都有时会出现，图片裁剪没问题但是没有加上水印的bug

**Comment by Agzer0** [comment]
返回的状态是完全成功

**Comment by jemygraw** [comment]
image没有参数，autoorient应该是 auto-orient

**Comment by Agzer0** [comment]
上面的那个策略我粘错了，这个编辑器自动把‘-’处理成换行了，我把原来的放出来
imageMogr2/auto-orient/format/jpg/thumbnail/750x/gravity/Center/crop/750x422|watermark/1/image/aHR0cDovL2ltZzAxLmlmZmFzaGlvbi5jbi9iYWNrc3RhZ2UvMjAxNy8wMTEwLzE1MDMzN183NTg3Mi5wbmc=/gravity/NorthWest/dx/0/dy/0|saveas/[saveas]

**Comment by jemygraw** [comment]
感觉是你的水印图片太大了啊，加个ws参数吧。 https://developer.qiniu.com/dora/manual/1316/image-watermarking-processing-watermark

**Comment by Agzer0** [comment]
试了下还是不可以
水印的图应该没关系，这种现象只是偶尔出现，这个策略大部分图片都是可以加上的
