### ISSUE TITLE
获取空间域名失败

### ISSUE THREAD

**Issue by Jamling** [qiniu/php-sdk#237]
使用java-java可以成功获取，但是使用php-sdk就返回空集合。以下是使用抓包工具包获取的请求信息。

GET /v6/domain/list?tble=temp HTTP/1.1
Host: api.qiniu.com
User-Agent: QiniuPHP/7.1.3 (Windows NT/i586) PHP/5.4.45
Accept: */*
Authorization: QBox 6utdCVaQ_E_4_74ydeKYAjQygXNMnu-9KP0QC14p:mcIPQC71PsD40hrM9H8DY2jvPF8=

HTTP/1.1 200 OK
Server: nginx
Date: Mon, 14 Aug 2017 05:39:12 GMT
Content-Type: application/json
Content-Length: 2
Connection: keep-alive
X-Log: ONE:1;APIS:8
X-Reqid: VQUAAA95j6zSn9oU
X-Reqid: VQUAAA95j6zSn9oU

[]

**Comment by jemygraw** [comment]
嗯，看上去是API写错了，我们修复下。

**Comment by Jamling** [comment]
响应速度好快！棒棒哒！
PS：php-sdk怎么指定像java-sdk里面的Zone.autoZone()， Zone.zone0()的区域呢？

**Comment by jemygraw** [comment]
在构造BucketManager或者其他Manager的时候指定。

**Comment by Jamling** [comment]
刚才重试了一下，发现还是无法获取。
请问这个API错误，应该是后台的api错误吧，php-sdk应该无需升级吧？

**Comment by jemygraw** [comment]
应该是 GET /v6/domain/list?tbl=temp

**Comment by Jamling** [comment]
这个无需你们修复，是我的错，没有注意到tbl参数名写错了。原生的php-sdk是没有domain/list这个api的。
