### ISSUE TITLE
关于上传文件打印字符串问题 

### ISSUE THREAD

**Issue by jasonjiang123** [qiniu/php-sdk#243]
文件地址： vendor/qiniu/php-sdk/src/Qiniu/Config.php
代码关键词：getZone
```php
private function getZone($accessKey, $bucket)
    {
        $cacheId = "$accessKey:$bucket";

        if (isset($this->zoneCache[$cacheId])) {
            // print("from cache\n");
            $zone = $this->zoneCache[$cacheId];
        } elseif (isset($this->zone)) {
            // print("from set\n");
            $zone = $this->zone;
            $this->zoneCache[$cacheId] = $zone;
        } else {
            // print("from query\n");
            $zone = Zone::queryZone($accessKey, $bucket);
            $this->zoneCache[$cacheId] = $zone;
        }
        return $zone;
    }
```
注释的打印代码

**Comment by ankadada** [comment]
您好，感谢反馈，会尽快提pr将其注释

**Comment by ankadada** [comment]
在最新的代码中已经将其注释了

**Comment by jasonjiang123** [comment]
OK

**Comment by jasonjiang123** [comment]
辛苦了

**Comment by cwl168** [comment]
文件地址： vendor/qiniu/php-sdk/src/Qiniu/Config.php
composer require qiniu/php-sdk  拉取的代码没有注释，

private function getZone($accessKey, $bucket)
    {
        $cacheId = "$accessKey:$bucket";

        if (isset($this->zoneCache[$cacheId])) {
            print("from cache\n");
            $zone = $this->zoneCache[$cacheId];
        } elseif (isset($this->zone)) {
            print("from set\n");
            $zone = $this->zone;
            $this->zoneCache[$cacheId] = $zone;
        } else {
            print("from query\n");
            $zone = Zone::queryZone($accessKey, $bucket);
            $this->zoneCache[$cacheId] = $zone;
        }
        return $zone;
    }

但是Github代码其实是已经注释！

**Comment by jemygraw** [comment]
已发布新版7.2.1，去除注释。
