### ISSUE TITLE
buildBatchMove 为静态方法

### ISSUE THREAD

**Issue by algery** [qiniu/php-sdk#251]
文档给的使用：
`$ops = $bucketManager->buildBatchMove($srcBucket, $keyPairs, $destBucket, true);`

**Comment by ankadada** [comment]
您好，这里主要是由于涉及到SDK中的结构涉及，所以采用了这种调用方式，感谢您的建议

**Comment by algery** [comment]
哇 还好回复之前去查了一下文档：`静态属性不能通过一个类已实例化的对象来访问（但静态方法可以）`  之前一直跟静态属性混在一起了，原来后面竟然还有一个括号；

**Comment by ankadada** [comment]
感谢对于七牛的支持
