### ISSUE TITLE
Zone::queryZone 方法返回错误

### ISSUE THREAD

**Issue by mrwzq** [qiniu/php-sdk#254]
如果bucket或者ak参数错误，Zone::queryZone方法会返回return array(null, new Error($url, $ret));数组

config.php 第42行 调用了$zone->srcUpHosts[0] ,导致报错
PHP Notice:  Trying to get property of non-object

**Comment by ankadada** [comment]
这是由于queryZone方法是通过bucket和ak参数调用接口来获取对应区域的域名，所以错误的话会得到错误数据导致报错

**Comment by mrwzq** [comment]
参数错误之后，是不是应当直接抛出异常或者其他方式处理，避免后续调用？

**Comment by ankadada** [comment]
不调用接口的话无法判断传入的参数是否存在问题

**Comment by q2211404** [comment]
我也遇到了, 说我空间错误 
{
"error": "no such bucket"
}

**Comment by ankadada** [comment]
这说明指定的空间不存在吧

**Comment by q2211404** [comment]
那也要返回个错误吧! 不然这样排查有困难

**Comment by ankadada** [comment]
返回了no such bucket吧，这个字面意思都是没有找到空间啊，而且返回的头信息里应该是会有状态码的，可以看一下
