### ISSUE TITLE
php sdk 待补充细节记录

### ISSUE THREAD

**Issue by xushiwei** [qiniu/php-sdk#26]
1.  https://github.com/qiniu/php-sdk/pull/21/files#L1L265 这里content-type得用putExtra里传进来的(PutExtra.MimeType)。参考 go sdk。
2. 上传还没有支持 x:custom_field - 用户自定义变量(PutExtra.Params)。
3. resumable io 还不支持重试(PutExtra.TryTimes)。
4. resumable io 还不支持通知(PutExtra.Notify/NotifyErr)。
5. batch api 测试不充分(需要测试 op=/delete/xxx 中含各种特殊字符比如'='等的情况)。

**Comment by longbai** [comment]
fixed in 7.0
