### ISSUE TITLE
PHP5.5.9 海外（法国）服务器上传文件不成功

### ISSUE THREAD

**Issue by JasonFun888** [qiniu/php-sdk#268]
Qiniu PHP-SDK Release 7.2.3，PHP5.5.9 海外（法国）服务器上传文件不成功！
$uploadManager->putFile 不成功，报错如下：
Qiniu\Http\Error Object
(
    [url:Qiniu\Http\Error:private] => http://
    [response:Qiniu\Http\Error:private] => Qiniu\Http\Response Object
        (
            [statusCode] => -1
            [headers] => Array
                (
                )
            [body] => 
            [error] => Could not resolve host: http
            [jsonData:Qiniu\Http\Response:private] => 
            [duration] => 0.028
        )
)
经调试发现原因是
0. UploadManager::putFile
1. FormUploader::put
2. Config::getUpHost
3. Config::getZone
4. Zone::queryZone
5.Response::json 的获取有问题，请排查！并及时提供修正方案！

**Comment by jemygraw** [comment]
这个应该是网络问题，麻烦重试看看能否解决。或者手动在Config对象里面指定具体机房对应的Zone

**Comment by JasonFun888** [comment]
如果重试能解决就不会提这个问题了呀，服务器是可以返回结果的，但是 5. Response::jsonData 为 NULL!

**Comment by JasonFun888** [comment]
问题已经查明根本原因出现在 Client::parseHeaders 方法上，里面的 “$kv[0] = ucwords($kv[0], '-');” 这一行，在 PHP 5.6 以下不支持第二参数，报一个Warning并会返回NULL！
由此导致 $headers 解析直接不正确，
然后 Response::__construct 构造方法里面调用的 if(self::isJson($headers)) 总为假，
进而不能给 $jsonData 赋值，其实请求是成功并且有响应的，只不过解析的时候出了差错。

**Comment by jemygraw** [comment]
有可能升级你的php版本吗

**Comment by JasonFun888** [comment]
不太可能升级，不过我发现 7.2.5 版SDK已经修复了这个问题!
