### ISSUE TITLE
UploadManager类104行调用FormUploader类静态方法put时参数列表个数不一致,$checkCrc参数多余，导致回调验证时文件名为空

### ISSUE THREAD

**Issue by ai4581532** [qiniu/php-sdk#272]
UploadManager类104行调用FormUploader类静态方法put时参数列表个数不一致，详情看下图
 

![image](https://user-images.githubusercontent.com/13961477/39857042-8cd891fc-5464-11e8-9f8d-bd21356c83c7.png)

![image](https://user-images.githubusercontent.com/13961477/39856982-6bd91d82-5464-11e8-91b9-409d523ae705.png)

**Comment by jemygraw** [comment]
已修复。准备发布7.2.5
