### ISSUE TITLE
v7.1.3 -> v7.2.3

### ISSUE THREAD

**Issue by ifreesec** [qiniu/php-sdk#273]
【纯吐槽】

vendor/qiniu/php-sdk/src/Qiniu/Processing/PersistentFop.php

![image](https://user-images.githubusercontent.com/25193980/40267028-58496ac6-5b88-11e8-916c-6ce21215ff11.png)

这 SDK 文件的修改也太暴力了吧，直接改方法的参数了

**Comment by jemygraw** [comment]
有设计不合理的地方，需要及时改正.
