### ISSUE TITLE
解析token错误

### ISSUE THREAD

**Issue by atlasman** [qiniu/php-sdk#275]
在src/Qiniu/functions.php 的 explodeUpToken 函数里面使用了base64_decode来解码uptoken，但\Qiniu\Auth 的uploadToken方法里编码uptoken的时候使用的是base64_urlSafeEncode函数进行编码，会出现解码错误的情况，建议把explodeUpToken函数里面的base64_decode 跟换为 functions.php 里面定义的 base64_urlSafeDecode。

**Comment by jemygraw** [comment]
谢谢反馈，已修复。
