### ISSUE TITLE
FormUploader::put 方法中的$key不是文件名

### ISSUE THREAD

**Issue by kwen8** [qiniu/php-sdk#279]
例如我执行：
```php
$uploader = new UploadManager($config)
$uploader->put($token, $key, $file);

```
得到的文件名是：
`{$key}/{$hashname}`

见图：
![image](https://user-images.githubusercontent.com/13549472/44192973-fc358400-a163-11e8-859f-b5aa9c6b8464.png)

![image](https://user-images.githubusercontent.com/13549472/44192985-05beec00-a164-11e8-8b2c-769e2ab4d721.png)

**Comment by jemygraw** [comment]
你看看你的$key指定的是什么

**Comment by forrest-mao** [comment]
$key 指定的是什么，上传的文件名就会是什么，如果有不方便在 issue 中描述的问题，可以提交工单 https://support.qiniu.com/tickets/new/ 来做处理
