### ISSUE TITLE
上传文件 Bad URL

### ISSUE THREAD

**Issue by ljf1172361058** [qiniu/php-sdk#283]
object(Qiniu\Http\Error)#11 (2) { ["url":"Qiniu\Http\Error":private]=> string(7) "http://" ["response":"Qiniu\Http\Error":private]=> object(Qiniu\Http\Response)#10 (6) { ["statusCode"]=> int(-1) ["headers"]=> array(0) { } ["body"]=> NULL ["error"]=> string(7) "Bad URL" ["jsonData":"Qiniu\Http\Response":private]=> NULL ["duration"]=> float(0) } }

**Comment by ConserveLee** [comment]
请问这个问题解决了吗

**Comment by ljf1172361058** [comment]
我现在已经没有做这个项目了,不过还是很谢谢你的回答
