### ISSUE TITLE
\Qiniu\json_decode($json) 能不能把json_decode改下名字？

### ISSUE THREAD

**Issue by sn01615** [qiniu/php-sdk#287]

**Comment by forrest-mao** [comment]
目前是使用 `\Qiniu\json_decode($json)` 遇到了什么具体的问题么，方便描述下吗

**Comment by sn01615** [comment]
> 目前是使用 `\Qiniu\json_decode($json)` 遇到了什么具体的问题么，方便描述下吗

没啥问题，容易和系统的json_decode混淆
