### ISSUE TITLE
PHP7.2.11 出现 Trying to get property 'srcUpHosts' of non-object

### ISSUE THREAD

**Issue by moell-peng** [qiniu/php-sdk#290]
错误信息: 
Trying to get property 'srcUpHosts' of non-object at /vendor/qiniu/php-sdk/src/Qiniu/Config.php:45

`Qiniu\Http\Client::sendRequest`  请求接口  https://api.qiniu.com/v2/query?ak=ak&bucket=bucket  时，未响应正确数据，个人编写 curl 代码在相同环境下数据响应正常， 代码如下：

```php
$url = 'https://api.qiniu.com/v2/query?ak=&bucket=';

$ch = curl_init(); 
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (compatible; MSIE 5.01; Windows NT 5.0)'); 
curl_setopt($curl,CURLOPT_SSL_VERIFYPEER, true);
curl_setopt($curl,CURLOPT_SSL_VERIFYHOST, true); 
curl_setopt($ch, CURLOPT_TIMEOUT, 15); 
$output = curl_exec($ch);
curl_close($ch);

var_dump($output);
```

类似问题：
#265 
#254

**Comment by fideism** [comment]
use Qiniu\Config;

$config = new Config();
$uploadManager = new UploadManager($config);
$uploadMgr->putFile($token, $key, $filePath);
我这样解决了

**Comment by nsnake** [comment]
> use Qiniu\Config;
> 
> $config = new Config();
> $uploadManager = new UploadManager($config);
> $uploadMgr->putFile($token, $key, $filePath);
> 我这样解决了

我按你的这样的写的，没用.....

**Comment by nsnake** [comment]
> 错误信息:
> Trying to get property 'srcUpHosts' of non-object at /vendor/qiniu/php-sdk/src/Qiniu/Config.php:45
> 
> `Qiniu\Http\Client::sendRequest` 请求接口 https://api.qiniu.com/v2/query?ak=ak&bucket=bucket 时，未响应正确数据，个人编写 curl 代码在相同环境下数据响应正常， 代码如下：
> 

我昨天尝试断点也发现是因为对sendRequest返回的数据结果没做错误处理。http状态是200,但内容其实是说配置信息有错误，而这个错误的信息又没被处理。
第116行
```
$ret = curl_errno($ch);
```
这里只检查了Http的错误，却并没检查内容的错误
而后直接就把内容返回了
```
return new Response($code, $duration, $headers, $body, null);
```
希望官方能修改下

**Comment by liaosy21** [comment]
@nsnake 我也曾经遇到过这个问题，后来发现是bucket名称搞错了，写对了就没问题了。
希望对你有用。

**Comment by generalbao** [comment]
> @moell-peng 我也曾经遇到过这个问题，后来发现是bucket名称搞错了，写对了就没问题了。
> 希望对你有用。

感谢感谢

**Comment by wsdo** [comment]
bucket名称搞错了
