### ISSUE TITLE
composer 安装时提示 guzzle/guzzle 已废弃

### ISSUE THREAD

**Issue by zaing** [qiniu/php-sdk#296]
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

**Comment by forrest-mao** [comment]
目前七牛的 SDK 还没有依赖 guzzle，https://github.com/qiniu/php-sdk/blob/master/composer.json 也没有相关依赖，是否是您项目其他的部分有依赖 guzzle

**Comment by timhbw** [comment]
经过进一步核实，目前七牛 SDK 没有依赖 guzzle/guzzle，您核实下是否是其他项目有依赖
