### ISSUE TITLE
前端上传，七牛回调到业务层，会将图片名带有特殊符号，如“.”，空格处理成 "_" 的解决办法

### ISSUE THREAD

**Issue by chunpat** [qiniu/php-sdk#298]
如题

**Comment by forrest-mao** [comment]
具体情况建议可以提供上传响应的空间名、文件名以及使用的 token 来进行复现，提交工单 https://support.qiniu.com/tickets/new/ 给七牛技术支持进行日志的排查，才好进行进一步的判断。

您复现后将相关信息提交到工单中，可以将工单号提供到 issue 中，我们来继续跟进。

**Comment by chunpat** [comment]
@forrest-mao 你好，这个问题已解决，随机生成不带"_"和“.”等特殊字符即可
