### ISSUE TITLE
zip文件,文件名包含"-"时;上传后的文件不能被解压

### ISSUE THREAD

**Issue by zsping1989** [qiniu/php-sdk#299]
上传zip文件,当文件名包含"-"号时,空间里面下载下来的zip格式文件不能被解压,文件损坏

**Comment by forrest-mao** [comment]
这个问题和 php sdk 好像不直接相关，您可以提供具体的访问链接，并提交工单 https://support.qiniu.com/tickets/new/ ，将工单号放到 issue 中，我们来继续跟进确认
