### ISSUE TITLE
你们版本号管理太不严谨了。

### ISSUE THREAD

**Issue by zgldh** [qiniu/php-sdk#304]
`FormUploader::put` 函数加了参数 `$checkCrc`，竟然只从 7.2.7 改成 7.2.8
还不加默认值。
这已经改变了该函数的调用方式了，应当升级版本号到 7.3.0 才对。

建议尽快为`$checkCrc`加上默认值 null。

**Comment by zgldh** [comment]
7.2.x 版本号，应当保证各函数接口调用方式的稳定性。

**Comment by zgldh** [comment]
而且 $checkCrc 竟然没有任何作用。玩儿呢？

**Comment by hhf666feng** [comment]
真的坑

**Comment by Qsnh** [comment]
版本意识不强，实力被坑

**Comment by ankadada** [comment]
实在抱歉，后续新参数的添加与版本发布会加强审核
