### ISSUE TITLE
code 400 error invalid multipart format: multipart: message too large

### ISSUE THREAD

**Issue by eeokee** [qiniu/php-sdk#310]
调用类 UploadManager  的 put 方法时，如果文件太大，比如大于50M，服务器会返回 invalid multipart format: multipart: message too large 错误，麻烦修复下，或者告知解决方法，谢谢

**Comment by ankadada** [comment]
超过50M的文件建议使用 UploadManager 中的 putFile 方法进行上传，这个会判断文件大小调用分片上传接口进上传

**Comment by eeokee** [comment]
嗯，谢谢回答，已经切换oss，结帖了。
