### ISSUE TITLE
header的Expect被覆盖导致文件无法上传

### ISSUE THREAD

**Issue by chendeben** [qiniu/php-sdk#313]
https://github.com/qiniu/php-sdk/blob/abf34f818bed04b3868f6953b1855d78aa90fa5c/src/Qiniu/Http/Client.php#L112
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Expect:'));这一行设定header的操作被后面的curl_setopt_array($ch, $options);覆盖了,会导致在新版本的libcurl下面,文件无法正常上传,烦请修复一下!

**Comment by chendeben** [comment]
经测试,改成以下代码可以正常上传:
`$headers = array();
        if (!empty($request->headers)) {
            foreach ($request->headers as $key => $val) {
                array_push($headers, "$key: $val");
            }
            $options[CURLOPT_HTTPHEADER] = $headers;
        }
        //七牛SDK此处有一个bug，Expert:不生效，会被后面的curl_setopt_array覆盖，导致文件无法上传
        //curl_setopt($ch, CURLOPT_HTTPHEADER, array('Expect:'));
        array_push($headers, "Expect:");
        $options[CURLOPT_HTTPHEADER] = $headers;


        if (!empty($request->body)) {
            $options[CURLOPT_POSTFIELDS] = $request->body;
        }
        curl_setopt_array($ch, $options);`

**Comment by forrest-mao** [comment]
您使用的 libcurl 是否方便帮忙提供下

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-979

**Comment by chendeben** [comment]
哈，我不是七牛员工，无法看到那个jira哈，然后，时间过去太久了，已经不知道对应的版本啦~

**Comment by timhbw** [comment]
好的，后续如果能够复现的话，可以提供下相关信息

目前这边测试的话无法复现呢
版本信息：
```
[root@centos7 ~]# curl -V
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.44 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets
```
 

测试结果：
```
[root@centos7 public]# php upload_test.php

====> putFile result:
array(2) {
["hash"]=>
string(28) "FlfP-b0j-g4MBQxBH79NLI3977yK"
["key"]=>
string(11) "favicon.ico"
}
```
