### ISSUE TITLE
上传时设置 MIME 不起作用呢

### ISSUE THREAD

**Issue by LIXiangChen** [qiniu/php-sdk#315]
`$uploadMgr->put($upToken, $key, 'balabala', null, 'application/json');`

这个 MIME 不生效, 仍旧是自动判断的.

**Comment by ankadada** [comment]
上传的字符串类型为application/octet-stream，你可以直接用文件上传试下看看，上传字符串要指定mime类型的话可以上传结束后调用接口修改mime类型
