### ISSUE TITLE
实时音视频云中的demo请求roomtoken，与我在phpsdk中请求的结果不一样，但是两边的参数是一样的

### ISSUE THREAD

**Issue by fengyefengxiang** [qiniu/php-sdk#316]
实时音视频云中的demo请求roomtoken，与我在phpsdk中请求的结果不一样，但是两边的参数是一样的
![image](https://user-images.githubusercontent.com/30484567/67186477-bbe22d80-f41a-11e9-8f7a-c9e283e42f5b.png)
![image](https://user-images.githubusercontent.com/30484567/67186520-d3211b00-f41a-11e9-84ef-552237bc0b51.png)
![image](https://user-images.githubusercontent.com/30484567/67186551-e207cd80-f41a-11e9-9eff-df34e964b9f1.png)

**Comment by fengyefengxiang** [comment]
请求管理帮看看解决下是什么问题
拜托了

**Comment by fengyefengxiang** [comment]
accessKey，与secretKey都是一样的，可以从roomtoken前端部分，第一个冒号之前可以看到结果是一样的

**Comment by fengyefengxiang** [comment]
肯能是因为版本的问题
我们现在用的是16年的版本，composer最新的版本获取就没有问题

**Comment by ankadada** [comment]
后台签算的参数前后拼接顺序和SDK的签算顺序不完全一致，所以会导致一样参数的情况下签算的token不一致的情况
