### ISSUE TITLE
获取文件信息示例有问题

### ISSUE THREAD

**Issue by shukyoo** [qiniu/php-sdk#323]
根据这个文档，获取文件信息
https://developer.qiniu.com/kodo/sdk/1241/php#rs-stat
运行后的结果返回：
[body] => {"error":"bad token"}
也没有token的参数啊，为什么会返回这个结果？

**Comment by forrest-mao** [comment]
这个表示用于调用 stat 接口的 token 有问题，需要看下密钥对是否设置正确，密钥对的获取在 https://portal.qiniu.com/user/key 中
