### ISSUE TITLE
Region.php华东机房api-z0.qiniu.com域名都没有？

### ISSUE THREAD

**Issue by pkkgu** [qiniu/php-sdk#326]
如题？

自己做异步第三方资源抓取，域名在SDK都里没找到。。。

**Comment by sy-records** [comment]
z0好像默认的就是api.qiniuc.com

**Comment by pkkgu** [comment]
@sy-records api.qiniuc.com 测试抓取地三方资源，提示域名什么的失败，换成api-z0.qiniu.com就OK了

**Comment by sy-records** [comment]
我提交了一个pr 你试试吧 我测试没问题



---原始邮件---
发件人: "pkkgu"<notifications@github.com&gt;
发送时间: 2020年4月11日(周六) 中午1:17
收件人: "qiniu/php-sdk"<php-sdk@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Luffy"<52o@qq52o.cn&gt;;
主题: Re: [qiniu/php-sdk] Region.php华东机房api-z0.qiniu.com域名都没有？ (#326)




 
@sy-records api.qiniuc.com 测试抓取地三方资源，提示域名什么的失败，换成api-z0.qiniu.com就OK了

**Comment by pkkgu** [comment]
@sy-records 等他们支持吧，我项目目前可以用。

**Comment by sy-records** [comment]
才发现，你用的域名就是错误。
`http://api.qiniuc.com/`这个就不存在
异步抓取的域名是在`api-<Zone>.qiniu.com`

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-977

**Comment by forrest-mao** [comment]
Duplicate of #301
