### ISSUE TITLE
人脸识别 返回的errormsg没有处理

### ISSUE THREAD

**Issue by vhvy** [qiniu/php-sdk#340]
人脸识别接口返回的错误信息 为errorcode 和 errormsg，而Qiniu\Http\Response 第111行 直接读取了`error`，导致会炸掉。

![image](https://user-images.githubusercontent.com/45645834/90119345-03f88500-dd8c-11ea-93b7-9ab6d13ea77f.png)
![image](https://user-images.githubusercontent.com/45645834/90119430-25f20780-dd8c-11ea-8655-27516924cb3a.png)
![image](https://user-images.githubusercontent.com/45645834/90119517-3dc98b80-dd8c-11ea-9603-975c281d317b.png)

**Comment by forrest-mao** [comment]
内部 issue：TS-1011

**Comment by timhbw** [comment]
可以用 ok() 方法根据状态码处理下，没读取到 error 也是不会异常的，会继续执行进行赋值
异常的话应该是调用姿势有问题导致的

示例代码：
```
private function post($url, $body)
{
$headers = $this->auth->authorizationV2($url, 'POST', $body, 'application/json');
$headers['Content-Type']='application/json';
$ret = Client::post($url, $body, $headers);

//可以根据状态码判断
if (!$ret->ok()) {
print("statusCode: " . $ret->statusCode);
return array(null, new Error($url, $ret));
}
$r = ($ret->body === null) ? array() : $ret->json();
return array($r, null);
}
}
```

然后返回
```
object(Qiniu\Http\Error)
private 'url' => string 'https://face-compare.qiniuapi.com/facecompare' 
private 'response' =>
object(Qiniu\Http\Response)
public 'statusCode' => int 400
public 'headers' =>
array
'Server' => string 'nginx'
'Date' => string 'Tue, 18 Aug 2020 05'
'Content-Type' => string 'application/json'
'Content-Length' => string '96'
'Connection' => string 'keep-alive'
'X-Log' => string 'COMMON-GATE'
'X-Reqid' => string 'ywYAANTieUm3RCwW'
'X-Resp-Code' => string '475'
public 'body' => string '{"session_id":"20200818051201JWOdDTquVo","Errorcode":55060038,"Errormsg":"IMAGEA_DECODE_FAILED"}' 
public 'error' => string '{"session_id":"20200818051201JWOdDTquVo","Errorcode":55060038,"Errormsg":"IMAGEA_DECODE_FAILED"}' 
.......
```

**Comment by vhvy** [comment]
> 可以用 ok() 方法根据状态码处理下，没读取到 error 也是不会异常的，会继续执行进行赋值
> 异常的话应该是调用姿势有问题导致的
> 
> 示例代码：
> 
> ```
> private function post($url, $body)
> {
> $headers = $this->auth->authorizationV2($url, 'POST', $body, 'application/json');
> $headers['Content-Type']='application/json';
> $ret = Client::post($url, $body, $headers);
> 
> //可以根据状态码判断
> if (!$ret->ok()) {
> print("statusCode: " . $ret->statusCode);
> return array(null, new Error($url, $ret));
> }
> $r = ($ret->body === null) ? array() : $ret->json();
> return array($r, null);
> }
> }
> ```
> 
> 然后返回
> 
> ```
> object(Qiniu\Http\Error)
> private 'url' => string 'https://face-compare.qiniuapi.com/facecompare' 
> private 'response' =>
> object(Qiniu\Http\Response)
> public 'statusCode' => int 400
> public 'headers' =>
> array
> 'Server' => string 'nginx'
> 'Date' => string 'Tue, 18 Aug 2020 05'
> 'Content-Type' => string 'application/json'
> 'Content-Length' => string '96'
> 'Connection' => string 'keep-alive'
> 'X-Log' => string 'COMMON-GATE'
> 'X-Reqid' => string 'ywYAANTieUm3RCwW'
> 'X-Resp-Code' => string '475'
> public 'body' => string '{"session_id":"20200818051201JWOdDTquVo","Errorcode":55060038,"Errormsg":"IMAGEA_DECODE_FAILED"}' 
> public 'error' => string '{"session_id":"20200818051201JWOdDTquVo","Errorcode":55060038,"Errormsg":"IMAGEA_DECODE_FAILED"}' 
> .......
> ```

🎉谢谢你。
