### ISSUE TITLE
缓存查询逻辑没有提供

### ISSUE THREAD

**Issue by curder** [qiniu/php-sdk#342]
你好，`src/Qiniu/Cdn/CdnManager.php`类提供了缓存的刷新，却没有提供缓存刷新查询的逻辑实现。

由于刷新缓存是异步操作，在提交刷新CDN缓存的请求后返回的 200，并不意味着CDN缓存已经刷新成功，当然也是可以通过bucket发送对应的事件到指定地址，但如果有多个bucket的话，都要设置一遍会比较麻烦。

建议添加一个缓存刷新查询日志，可以清晰的列出提交刷新CND缓存的情况。

接口地址

`/v2/tune/refresh/list`

详见这里：https://developer.qiniu.com/fusion/api/1229/cache-refresh

**Comment by curder** [comment]
已经提了PR，请在合适的时间合并下代码。

**Comment by timhbw** [comment]
您好，这边后续会进行查看。但是由于 CI 限制，其他仓库下提交的 PR 无法解析密钥，导致测试用例中的 sk 参数丢失，所以 CI 过不去，这边会审核代码后手动进行提交合并

**Comment by timhbw** [comment]
update at https://github.com/qiniu/php-sdk/pull/344
