### ISSUE TITLE
新版qiniu/php-sdk v7.3.0删除资源返回结果与v7.2.10不兼容导致程序出错

### ISSUE THREAD

**Issue by aoyoo111** [qiniu/php-sdk#350]
新版qiniu/php-sdk v7.3.0删除资源返回结果与v7.2.10不兼容:
$res = $bucketManager->delete($config['bucket'], $file);
v7.3.0版删除资源后返回数组
`array(2) {
  [0] => NULL
  [1] => NULL
}`
v7.2.10版删除资源后返回
`NULL`

1.使用如下判断存在错误
` if (!is_null($res) || $res !== null) {
            return [
                'data'=> '删除qiniu文件失败',
                'status'=> false
            ];
        } else {
            return [
                'data'=> '删除成功',
                'status'=> true
            ];
        }`
2. 请问v7.3.0版返回的数组下标0和1分别表示什么?该如何判断是否删除成功,谢谢

**Comment by timhbw** [comment]
- 新版本把方法的返回值统一为数组形式了
- 放到数组里面就可以了，判断语句不用变，比如：
```
list($ret, $err) = $bucketManager->delete($bucket, $key);
if ($err !== null) {
    var_dump($err);
} else {
    var_dump($ret);
```

**Comment by aoyoo111** [comment]
@timhbw 感谢回复，我试一下看看！
