### ISSUE TITLE
请问删除资源中的文件，返回的$err的数据类型是什么

### ISSUE THREAD

**Issue by aiyuchen** [qiniu/php-sdk#354]
代码如下
```
        $auth = new QiniuAuth(
            env('QINIU_ACCESS'), env('QINIU_SECRET')
        );

        $config = new QiniuConfig();
        $bucketManager = new BucketManager($auth, $config);

        $bucket = env('ATTACH_BUCKET');
        $err = $bucketManager->delete($bucket, $key);

        dd($err);
```
测试了两遍，分别如下
--------------------------
删除成功返回
```
array:2 [
  0 => null
  1 => null
]
```
删除失败返回
```
array:2 [
  0 => null
  1 => Qiniu\Http\Error^ {}
]
```

1. 第一个参数是什么意思，成功和失败都返回`null`
2. 第二个参数从字面上看是不是一个异常`Exception`，文档里好像没有关于`Qiniu\Http\Erro`说明

**Comment by wrs13634194612** [comment]
https://www.zhihu.com/question/21349573  这篇问答可以解决你的问题

**Comment by lihsai0** [comment]
@aiyuchen

> 第一个参数是什么意思，成功和失败都返回null

第一个参数是服务端响应的 body 信息，**成功时**，如果服务端没有响应任何信息则为 null，如果返回了信息则为 json 数据。

> 第二个参数从字面上看是不是一个异常Exception，文档里好像没有关于Qiniu\Http\Erro说明

否，为自定义 Error 类。以 `list($ret, $err) = $bucketManager->delete($bucket, $key);` 为例，该类上有如下几个方法可调用

- `$err -> code()` 返回 HTTP Code
- `$err -> message()` 返回错误信息
- `$err -> getResponse()` 返回 Qiniu\Http\Response 的实例

如果还有其他疑问欢迎随时重新打开这个 issue
