### ISSUE TITLE
Http/Header 里private static function isValidKeyName($str)函数报错问题

### ISSUE THREAD

**Issue by doghap** [qiniu/php-sdk#374]
问题报错原因是count()函数只对Countable或数组有效，而字符串则需要用strlen()函数去求长度
https://github.com/qiniu/php-sdk/blob/dd4b3d34120f5b1e9cd2c4f1c396e170fbf15192/src/Qiniu/Http/Header.php?_pjax=%23js-repo-pjax-container#L265

**Comment by doghap** [comment]
具体错误为：count(): Parameter must be an array or an object that implements Countable

**Comment by lihsai0** [comment]
@doghap 感谢反馈！:pray:
