### ISSUE TITLE
  count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by dongdong7** [qiniu/php-sdk#379]
![WX20220303-101857](https://user-images.githubusercontent.com/230118/156483658-871334ee-b283-4004-9a99-c0bb25ca4ce5.png)

PHP版本是：PHP 7.4.24 (cli) (built: Sep 24 2021 00:16:53) ( NTS )

**Comment by lihsai0** [comment]
@dongdong7 抱歉造成困扰，#378 修复，可能过阵子才能发布。

在发布之前可以：
- 降低 PHP 版本
- 使用低一个版本的 SDK
- 直接修改一下此处代码

**Comment by xuanyanwow** [comment]
我在PR 377已经解决，可惜没有合并处理  响应速度较慢 哈哈哈哈

**Comment by zhuaiwhh** [comment]
if(count((array)$body) > 0

**Comment by neatstudio** [comment]
哈哈。同款问题。我现在只能在代码里临时error_reporting(0)了
```
$report = error_reporting(0);
//....code
error_reporting($report);
```

**Comment by zhaozhentao** [comment]
赶紧更新呀，太慢了

**Comment by tomener** [comment]
今天一大早就踩到这个坑
