### ISSUE TITLE
SDK中的myclabs/php-enum枚举类软件包1.6.6已不兼容PHP8.1版本希望可以兼容一下

### ISSUE THREAD

**Issue by whd-source** [qiniu/php-sdk#396]
![image](https://user-images.githubusercontent.com/19921310/188851604-36a13c1c-cbaf-4542-a378-e59a01e56345.png)

**Comment by tourze** [comment]
短时间，貌似只能降到v7.4.1，哎

**Comment by bachue** [comment]
@tourze  之后会做大版本升级来支持 PHP v8.x 的

**Comment by tourze** [comment]
> 短时间，貌似只能降到v7.4.1，哎

请问有计划推荐这个吗。。

**Comment by tourze** [comment]
> @tourze @whd-source 可以尝试下 https://packagist.org/packages/qiniu/php-sdk#v7.9.0

简单测试上传，没什么问题
