### ISSUE TITLE
php8.1上传视频报错

### ISSUE THREAD

**Issue by pasawu** [qiniu/php-sdk#406]
During inheritance of JsonSerializable: Uncaught think\\exception\\ErrorException: Return type of MyCLabs\\Enum\\Enum::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/wwwroot/ke.mingziwang.cn/vendor/myclabs/php-enum/src/Enum.php:200\nStack trace:\n#0 /opt/wwwroot/ke.mingziwang.cn/vendor/myclabs/php-enum/src/Enum.php(18): think\\initializer\\Error->appError()\n#1 /opt/wwwroot/ke.mingziwang.cn/vendor/composer/ClassLoader.php(480): include('...')\n#2 /opt/wwwroot/ke.mingziwang.cn/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile()\n#3 /opt/wwwroot/ke.mingziwang.cn/vendor/qiniu/php-sdk/src/Qiniu/Enum/QiniuEnum.php(12): Composer\\Autoload\\ClassLoader->loadClass()\n#4 /opt/wwwroot/ke.mingziwang.cn/vendor/composer/ClassLoader.php(480): include('...')\n#5 /opt/wwwroot/ke.mingziwang.cn/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile()\n#6 /opt/wwwroot/ke.mingziwang.cn/vendor/qiniu/php-sdk/src/Qiniu/Enum/SplitUploadVersion.php(5): Composer\\Autoload\\ClassLoader->loadClass()\n#7 /opt/wwwroot/ke.mingziwang.cn/vendor/composer/ClassLoader.php(480): include('...')\n#8 /opt/wwwroot/ke.mingziwang.cn/vendor/composer/ClassLoader.php(346): Composer\\Autoload\\includeFile()\n#9 /opt/wwwroot/ke.mingziwang.cn/vendor/qiniu/php-sdk/src/Qiniu/Storage/ResumeUploader.php(90): Composer\\Autoload\\ClassLoader->loadClass()\n#10 /opt/wwwroot/ke.mingziwang.cn/vendor/qiniu/php-sd

php8.1上传视频报错，php8.0正常

**Comment by pasawu** [comment]
"qiniu/php-sdk": "^7.7"

**Comment by lihsai0** [comment]
感谢反馈！

已于 #405 修复，请等待新版本发布。

**Comment by bachue** [comment]
@pasawu  可以尝试下 https://packagist.org/packages/qiniu/php-sdk#v7.9.0
