### ISSUE TITLE
希望增加一个按文件类型枚举文件列表的API

### ISSUE THREAD

**Issue by 490626721** [qiniu/php-sdk#411]
希望增加一个按文件类型枚举文件列表的API，比如我只想获取空间内的图片资源或者视频资源

**Comment by lihsai0** [comment]
@490626721 

后端暂时没有这种功能，SDK 做的话也是列出来所有再过滤，所以大概率不会提供这样的 API。

建议您提前做好分类规划，例如：

- 将图片资源与视频资源放在不同的 bucket 中；
- 将图片资源与视频资源放在不同的前缀路径中，如 images/xxx.png, vidoes/xxx.mp4，随后使用前缀（images, videos）枚举文件。

**Comment by 490626721** [comment]
这样的啊，感谢！
